### ISSUE TITLE
Update the about description of the project

### ISSUE THREAD

**Issue by Jonasvdbo** [alliander-opensource/measure#4]
**Is your feature request related to a problem? Please describe.**
The current about description of the project does not make full clear what the scope and purpose of the project is.
![image](https://user-images.githubusercontent.com/3628277/176865995-411a9fff-a184-4f2e-b45f-7b9824b6aa5d.png)

**Describe the solution you'd like**
My suggestion would be to change the about description to somethink like "measure is a Kotlin library for working with units of measurement that are ofter used in the power system sector."

**Comment by dvberkel** [comment]
I agree that the project could use a better description.

Your suggestions are overly restrictive. The artifacts from this repository can be used outside the power sector.

We will address the disclosure of the purpose of the project with better documentation. For example listing companies that rely on these artifacts.

**Comment by Jonasvdbo** [comment]
Ok. I understand your point of view and I agree that my suggestion is maybe too spefic. Maybe a better suggestions for myside would be to change the describtion to somethink like: "measure is a Kotlin library for working with units of measurementor or "measure is a Kotlin library for working with units of measurement that for example used in the power system sector."

**Comment by Jonasvdbo** [comment]
@dvberkel I am just following up to check what you think of my adjusted suggestion for the project description based on your feedback.

**Comment by dvberkel** [comment]
I am considering your suggestion. I am still on the fence

**Comment by dvberkel** [comment]
This description was changed to better reflect the intended use
