### ISSUE TITLE
Update the name of the project

### ISSUE THREAD

**Issue by Jonasvdbo** [alliander-opensource/measure#5]
**Is your feature request related to a problem? Please describe.**
The current name of the project is very generic.  Maybe a more specifc name will help to make it more clear what the goal and purpose is of this project.

For example if you search on measure on github, you will find many project with the name measure:

![image](https://user-images.githubusercontent.com/3628277/176867796-876be6eb-7405-4836-a819-40c61cc6b3ff.png)

**Describe the solution you'd like**
My suggestion would be to change it to for example Units-of-measurement-for-Power-systems or Units-of-measurement-for-Energy or Units-of-measurement-for-electric-grids

**Comment by dvberkel** [comment]
Thanks for your suggestion.

I do think that the project could have a clearer description of it's purpose. I don't think it will need a distinct name.
First of all, names on GitHub are already name-spaced by organization so names do not clash.
Furthermore, your suggestions are overly specific. The artifacts for this repository are not only usable in the Energy domain.

The path that I would see to address the clearer purpose for this project is in better descriptions and labels for this project

**Comment by Jonasvdbo** [comment]
Ok. I understand your point of view and maybe my suggestions were too specific. What about the suggestion to change it to Units-of-measurement in stead? Than it is not limited to the energy domain and at the same time create more clearness to potential users.

Futhermore I also support your idea to have better descriptions and labels for this project.

**Comment by Jonasvdbo** [comment]
@dvberkel I am just following up to check what you think of my adjusted suggestion for the project name based on your feedback.
